/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ee05e8c3-691b-49b1-af1e-0e2204a1c303",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_SKU6WmWTb",
    "aws_user_pools_web_client_id": "12j6k7qk8n3fioi1l4bl0t54ln",
    "oauth": {},
    "aws_user_files_s3_bucket": "mybookstore16979f0e8a5104d1c8481f232511a4b67103604-prod",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://6wy5d634dbgcbljkq325ce2izm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-piyymgkb5bhqrda4it3d3rftci",
    "aws_content_delivery_bucket": "mybookstore1-20220516124134-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://mybookstore1-20220516124134-hostingbucket-prod.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
